# RSS検証機能付きの新情報源発見ワークフロー例
# .github/workflows/discover_sources.yml の拡張版

name: Enhanced Source Discovery with RSS Validation

on:
  schedule:
    - cron: '0 10 * * 0'  # 毎週日曜日 10:00 UTC (19:00 JST)
  workflow_dispatch:

jobs:
  discover-and-validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install requests feedparser beautifulsoup4 openai supabase
        
    - name: Run enhanced source discovery
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd scripts
        
        # 1. 新情報源を発見（RSS検証付き）
        python discover_gpt_categories_enhanced.py
        
        # 2. 発見結果をレポート
        echo "## 📊 RSS検証結果サマリー" >> discovery_report.md
        python -c "
        import json
        with open('discovery_results.json', 'r') as f:
            results = json.load(f)
        
        auto_count = sum(1 for r in results if r.get('acquisition_mode') == 'auto')
        manual_count = sum(1 for r in results if r.get('acquisition_mode') == 'manual')
        disabled_count = sum(1 for r in results if r.get('acquisition_mode') == 'disabled')
        
        print(f'- 🤖 自動収集可能: {auto_count}個')
        print(f'- 👤 手動チェック推奨: {manual_count}個') 
        print(f'- ❌ 無効/スキップ: {disabled_count}個')
        print(f'- 📊 総発見数: {len(results)}個')
        " >> discovery_report.md
        
        # 3. Pull Request作成
        if [ -f "new_sources.sql" ]; then
          python create_enhanced_pr.py
        fi
        
    - name: Archive discovery results
      uses: actions/upload-artifact@v3
      with:
        name: discovery-results
        path: |
          scripts/discovery_report.md
          scripts/discovery_results.json
          scripts/rss_validation_log.txt